version: '2'
services:
    amandaoa-app:
        image: amandaoa
        external_links:
            - amandaoa-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/amandaoa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    amandaoa-mysql:
        extends:
            file: mysql.yml
            service: amandaoa-mysql
